class_name GameAudio
extends Node

# Every clip is generated by tools/make_sfx.py; see that script to re-tune them.
const CLIP_DIR := "res://assets/audio/"
const CLIPS := [
	&"dig", &"coffee", &"filter_land", &"squash", &"life_lost", &"life_gained",
	&"level_clear", &"close_call", &"reshuffle", &"enemy_respawn", &"ui", &"start",
]
# Per-clip trim in dB. Digging fires on every step, so it sits far back; the
# rare, important events are allowed to be loud.
const CLIP_VOLUME := {
	&"dig": -17.0,
	&"coffee": -6.0,
	&"filter_land": -8.0,
	&"squash": -6.0,
	&"life_lost": -3.0,
	&"life_gained": -4.0,
	&"level_clear": -3.0,
	&"close_call": -13.0,
	&"reshuffle": -5.0,
	&"enemy_respawn": -8.0,
	&"ui": -10.0,
	&"start": -6.0,
}
# Enough voices that a filter landing on three pods at once still sounds like three.
const VOICE_COUNT := 12

var streams: Dictionary = {}
var voices: Array[AudioStreamPlayer] = []
var next_voice := 0
var muted := false


func _ready() -> void:
	for clip_name in CLIPS:
		var path: String = CLIP_DIR + String(clip_name) + ".wav"
		# A missing import (fresh checkout, never opened in the editor) must not
		# take the game down; it just plays silently.
		if ResourceLoader.exists(path):
			streams[clip_name] = load(path)
	for voice_index in range(VOICE_COUNT):
		var voice := AudioStreamPlayer.new()
		add_child(voice)
		voices.append(voice)


func play(clip_name: StringName, pitch := 1.0) -> void:
	if muted or not streams.has(clip_name) or voices.is_empty():
		return
	var voice := voices[next_voice]
	next_voice = (next_voice + 1) % voices.size()
	voice.stream = streams[clip_name]
	voice.volume_db = CLIP_VOLUME.get(clip_name, -6.0)
	voice.pitch_scale = clampf(pitch, 0.25, 4.0)
	voice.play()


func set_muted(value: bool) -> void:
	muted = value
	if muted:
		for voice in voices:
			voice.stop()
